// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Fvect.Backend.Data.Database.Migrations
{
    [DbContext(typeof(FvectContext))]
    [Migration("20200310202441_AddPrimeNumbersTable")]
    partial class AddPrimeNumbersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FVect.Backend.Data.Database.Model.PrimeNumber", b =>
                {
                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Value");

                    b.ToTable("PrimeNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
